// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9PQcl8cjCgRipbIo9008XNsEhRvArSPs',
    appId: '1:590681255702:web:3c619ea01d495f1a1d2a37',
    messagingSenderId: '590681255702',
    projectId: 'my-quick-buy',
    authDomain: 'my-quick-buy.firebaseapp.com',
    storageBucket: 'my-quick-buy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGcTpARCDBY0rvEsxU2MFEl2D69i2H8cU',
    appId: '1:590681255702:android:2df020bf939604d01d2a37',
    messagingSenderId: '590681255702',
    projectId: 'my-quick-buy',
    storageBucket: 'my-quick-buy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWs5GJGbZ3L_xzXX_GINGiPRHjDGHUhtE',
    appId: '1:590681255702:ios:b9fe35990273888e1d2a37',
    messagingSenderId: '590681255702',
    projectId: 'my-quick-buy',
    storageBucket: 'my-quick-buy.firebasestorage.app',
    iosBundleId: 'com.example.quickBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWs5GJGbZ3L_xzXX_GINGiPRHjDGHUhtE',
    appId: '1:590681255702:ios:b9fe35990273888e1d2a37',
    messagingSenderId: '590681255702',
    projectId: 'my-quick-buy',
    storageBucket: 'my-quick-buy.firebasestorage.app',
    iosBundleId: 'com.example.quickBuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9PQcl8cjCgRipbIo9008XNsEhRvArSPs',
    appId: '1:590681255702:web:bffb27fb0788e5ab1d2a37',
    messagingSenderId: '590681255702',
    projectId: 'my-quick-buy',
    authDomain: 'my-quick-buy.firebaseapp.com',
    storageBucket: 'my-quick-buy.firebasestorage.app',
  );
}
